Feature comments
MadeOfSt0ne/java-explore-with-me pull request #3
Opened 2022-10-04 15:18 UTC by MadeOfSt0ne

2022-10-04 15:28 UTC, vbutrim commented on README.md
> +6. Дополнительная функциональность
лайк

2022-10-04 15:28 UTC, vbutrim commented on README.md
> +   просматривать все свои комментарии. Администраторы ресурса также могут редактировать и удалять комментарии. Помимо
"редактировать" звучит как цензура 🤔

2022-10-04 15:30 UTC, vbutrim commented on server/src/main/java/ru/practicum/explore/controllers/admin/AdminCommentController.java
> +        log.info("ADMIN: Edit comment={} with text={}", commentId, text);
[nit] префикс "ADMIN" необязателен. можно настроить log4j так, чтобы он логировал название класса, откуда было залогировано сообщение, каждый раз

2022-10-04 15:31 UTC, vbutrim commented on server/src/main/java/ru/practicum/explore/controllers/admin/AdminCommentController.java
> +public class AdminCommentController {
[nit] я бы Admin сделал бы суффиксом -- CommentAdminController

сейчас AdminCommentController переводится как контроллер админского комментария, а ожидаем админский контроллер комментария)

2022-10-04 15:37 UTC, vbutrim commented on server/src/main/java/ru/practicum/explore/controllers/admin/AdminCommentController.java
> +        log.info("ADMIN: Edit comment={} with text={}", commentId, text);
[nit] лучше уровень логирования дебаг, чтобы не засорять логи и в случае чего отключить эти строки

2022-10-04 15:39 UTC, vbutrim commented on stats/src/main/java/ru/practicum/stats/utils/DateTimeFormat/DateTimeFormat.java
> +public class DateTimeFormat {
[nit] можно просто DateUtils и положить на уровень выше

2022-10-04 15:42 UTC, vbutrim commented on stats/src/main/java/ru/practicum/stats/utils/DateTimeFormat/DateTimeFormat.java
> +public class DateTimeFormat {
совпадает с одноименным классом из рядом лежащего модуля.
почему бы не вынести единственный класс в общий модуль и переиспользовать?

2022-10-04 15:46 UTC, vbutrim commented on server/src/main/java/ru/practicum/explore/models/event/dto/EventShortDto.java
> +    private List<Comment> commentList;
[nit] достаточно comments

2022-10-04 15:55 UTC, MadeOfSt0ne commented on README.md
> +   просматривать все свои комментарии. Администраторы ресурса также могут редактировать и удалять комментарии. Помимо
цензура и есть =)

2022-10-05 10:02 UTC, vbutrim commented on server/src/main/java/ru/practicum/explore/controllers/admin/AdminCommentController.java
> +@RequestMapping(path = "/admin/comments/{commentId}")
классное API

2022-10-05 10:02 UTC, vbutrim commented on server/src/main/java/ru/practicum/explore/controllers/admin/AdminCommentController.java
> +                                    @RequestParam(value = "text") String text) {
лучше сразу в тело запроса.
непонятно, сколько символов будет аллоцировано под текст

2022-10-05 10:03 UTC, vbutrim commented on server/src/main/java/ru/practicum/explore/controllers/client/PrivateCommentController.java
> +                                    @RequestParam(value = "text") String text) {
лучше сразу в тело

_применимо на patch также_

2022-10-05 10:04 UTC, MadeOfSt0ne commented on server/src/main/java/ru/practicum/explore/controllers/admin/AdminCommentController.java
> +                                    @RequestParam(value = "text") String text) {
даже если в теле будет одна строка?

2022-10-05 10:05 UTC, vbutrim commented on server/src/main/java/ru/practicum/explore/controllers/client/PrivateCommentController.java
> +    @PostMapping(path = "/{eventId}")
сейчас префикс получается

/users/{userId}/comments/{eventId}
, что клашится с 
/users/{userId}/comments/{commentId}

как думаешь, на какой эндпоинт будет передан реквест /users/123/comments/456?

2022-10-05 10:05 UTC, vbutrim commented on server/src/main/java/ru/practicum/explore/controllers/client/PrivateCommentController.java
> +    @GetMapping(path = "/own")
можно оставить просто
/users/{userId}/comments

2022-10-05 10:06 UTC, vbutrim commented on server/src/main/java/ru/practicum/explore/mappers/CommentMapper.java
> +                new CommentDto.UserDto(comment.getAuthor().getId(), comment.getAuthor().getName()),
почему не перегрузить конструктор, чтобы принимал только Author-а

_применимо для event также_

2022-10-05 10:06 UTC, vbutrim commented on server/src/main/java/ru/practicum/explore/mappers/CommentMapper.java
> +    public static Comment toComment(String text, User author, Event event) {
кайф

2022-10-05 10:07 UTC, vbutrim commented on server/src/main/java/ru/practicum/explore/models/event/Event.java
> +    private List<Comment> comments;
сомневаюсь, что надо доставать комментарии всегда, ну ок

2022-10-05 10:07 UTC, vbutrim commented on server/src/main/java/ru/practicum/explore/services/admin/AdminCommentService.java
> +    CommentDto editComment(long commentId, String text);
сервис должен возвращать доменный объект и никак не dto

2022-10-05 10:08 UTC, vbutrim commented on server/src/main/java/ru/practicum/explore/services/admin/AdminCommentService.java
> +public interface AdminCommentService {
зачем нужен интерфейс с единственной имплементацией?

2022-10-05 10:08 UTC, vbutrim commented on server/src/main/java/ru/practicum/explore/services/admin/impl/AdminCommentServiceImpl.java
> +public class AdminCommentServiceImpl implements AdminCommentService {
*Impl считается устаревшим неймингом, что не несет никакого смысла. старайся избегать его

2022-10-05 10:09 UTC, vbutrim commented on server/src/main/java/ru/practicum/explore/services/admin/impl/AdminCommentServiceImpl.java
> +public class AdminCommentServiceImpl implements AdminCommentService {
_применимо для PrivateCommentService_

2022-10-05 10:09 UTC, vbutrim commented on server/src/main/java/ru/practicum/explore/services/admin/AdminCommentService.java
> +public interface AdminCommentService {
_применимо для PrivateCommentService_

2022-10-05 10:09 UTC, vbutrim commented on server/src/main/java/ru/practicum/explore/services/client/PrivateCommentService.java
> +    List<CommentDto> getComments(long userId);
что будет, если комментариев пользователя будет оч много?

2022-10-05 10:10 UTC, vbutrim commented on server/src/main/java/ru/practicum/explore/services/client/impl/PrivateCommentServiceImpl.java
> +    public CommentDto editComment(long userId, long commentId, String text) {
[nit] я бы запрещал любые действия, если пользователь забанен, включая изменение/удаление комментариев

2022-10-05 10:11 UTC, vbutrim requested changes
оч много оффтопа
предметно -- гуд стафф
оставил несколько замечаний

2022-10-08 09:40 UTC, MadeOfSt0ne commented on server/src/main/java/ru/practicum/explore/controllers/admin/AdminCommentController.java
> +        log.info("ADMIN: Edit comment={} with text={}", commentId, text);
буду знать!

2022-10-08 09:40 UTC, MadeOfSt0ne commented on server/src/main/java/ru/practicum/explore/controllers/admin/AdminCommentController.java
> +public class AdminCommentController {
ох уж эти тонкости языка =)

2022-10-08 09:41 UTC, MadeOfSt0ne commented on server/src/main/java/ru/practicum/explore/controllers/admin/AdminCommentController.java
> +        log.info("ADMIN: Edit comment={} with text={}", commentId, text);
учту на будущее

2022-10-08 09:48 UTC, MadeOfSt0ne commented on stats/src/main/java/ru/practicum/stats/utils/DateTimeFormat/DateTimeFormat.java
> +public class DateTimeFormat {
вынес на уровень выше

2022-10-08 09:53 UTC, MadeOfSt0ne commented on stats/src/main/java/ru/practicum/stats/utils/DateTimeFormat/DateTimeFormat.java
> +public class DateTimeFormat {
тут не совсем понятно: делать целый модуль (как сервис и статистика) ради одного форматера? у каждого модуля могут быть свои настройки, просто у меня настройки совпадают.

2022-10-08 09:54 UTC, MadeOfSt0ne commented on server/src/main/java/ru/practicum/explore/models/event/dto/EventShortDto.java
> +    private List<Comment> commentList;
ok

2022-10-08 09:58 UTC, MadeOfSt0ne commented on server/src/main/java/ru/practicum/explore/controllers/client/PrivateCommentController.java
> +    @PostMapping(path = "/{eventId}")
упс =\ добавил new в путь для нового комента

2022-10-08 09:59 UTC, MadeOfSt0ne commented on server/src/main/java/ru/practicum/explore/controllers/client/PrivateCommentController.java
> +    @GetMapping(path = "/own")
согласен. исправил.

2022-10-08 10:08 UTC, MadeOfSt0ne commented on server/src/main/java/ru/practicum/explore/models/event/Event.java
> +    private List<Comment> comments;
действительно, они нужны не всегда. сменил на lazy

2022-10-08 10:09 UTC, MadeOfSt0ne commented on server/src/main/java/ru/practicum/explore/services/admin/impl/AdminCommentServiceImpl.java
> +public class AdminCommentServiceImpl implements AdminCommentService {
это уже в крови =) буду стараться

2022-10-08 10:17 UTC, MadeOfSt0ne commented on server/src/main/java/ru/practicum/explore/mappers/CommentMapper.java
> +                new CommentDto.UserDto(comment.getAuthor().getId(), comment.getAuthor().getName()),
круто!

2022-10-08 10:30 UTC, MadeOfSt0ne commented on server/src/main/java/ru/practicum/explore/services/admin/AdminCommentService.java
> +    CommentDto editComment(long commentId, String text);
О_О У меня все сервисы берут объект из бд, идут с ним в маппер и возвращают контроллеру дто. Ты предлагаешь сервису отдавать объект, а потом контроллер пусть ходит с ним в маппер и возвращает дто? Могу и так сделать. А в чем разница???

2022-10-08 10:34 UTC, MadeOfSt0ne commented on server/src/main/java/ru/practicum/explore/controllers/client/PrivateCommentController.java
> +                                    @RequestParam(value = "text") String text) {
переделал на тело

2022-10-08 10:39 UTC, MadeOfSt0ne commented on server/src/main/java/ru/practicum/explore/services/admin/AdminCommentService.java
> +public interface AdminCommentService {
как понять когда нужен интерфейс, а когда - нет?? у меня все сервисы разделены на приватные и админские, у всех по одной имплементации.

2022-10-08 10:44 UTC, MadeOfSt0ne commented on server/src/main/java/ru/practicum/explore/services/client/impl/PrivateCommentServiceImpl.java
> +    public CommentDto editComment(long userId, long commentId, String text) {
это моя недоработка. исправил.

2022-10-08 10:51 UTC, MadeOfSt0ne commented on server/src/main/java/ru/practicum/explore/services/client/PrivateCommentService.java
> +    List<CommentDto> getComments(long userId);
добавил постраничное отображение

2022-10-08 20:25 UTC, vbutrim commented on stats/src/main/java/ru/practicum/stats/utils/DateTimeFormat/DateTimeFormat.java
> +public class DateTimeFormat {
> делать целый модуль (как сервис и статистика) ради одного форматера?

ага. у тебя скорее всего эти настройки будут шариться на всем проекте.

2022-10-08 20:25 UTC, vbutrim commented on server/src/main/java/ru/practicum/explore/controllers/admin/AdminCommentController.java
> +                                    @RequestParam(value = "text") String text) {
ага, именно

2022-10-08 20:32 UTC, vbutrim commented on server/src/main/java/ru/practicum/explore/services/admin/AdminCommentService.java
> +    CommentDto editComment(long commentId, String text);
> Ты предлагаешь сервису отдавать объект, а потом контроллер пусть ходит с ним в маппер и возвращает дто?

да, именно.

>  А в чем разница???

Разница в переиспользовании. Если у тебя будешь еще один потребитель сервиса (будь то еще один контроллер, другой сервис, что-либо еще), при текущем раскладе ты будешь возвращать dto. Хорошо, если dto требуется одна и та же. А если нет? А ведь может еще требоваться какая-то логика, а накручивать доменную логику на dto -- не круто. 
А еще представь, что разработкой занимаешься не только ты, и твой сокомандник не знает про то, что доменной логики не должно быть над dto, забил и стал оперировать dto. _Тут начинается каша_.

Стоит программировать код так, чтобы требовалось минимальное изменение для его расширения. Лучше всего, если при масштабировании и добавлении функционала будет добавляться новый код и не изменяться сразу (Open-Closed principle из SOLID). В данном случае, оперируя сразу доменным объектом в сервисе, мы способствуем следованию этого принципа.

2022-10-08 20:33 UTC, vbutrim commented on server/src/main/java/ru/practicum/explore/services/admin/AdminCommentService.java
> +public interface AdminCommentService {
Критерий может быть таким -- когда у интерфейса больше одного наследника.
Или же когда ты хочешь подчеркнуть, что у класса именно такой интерфейс. 

В данном случае интерфейс тривиален и совсем не требуется, а с учетом того, что его имплементация еще и название_интерфейса_Impl, то он скорее путает

2022-10-08 20:33 UTC, vbutrim commented on server/src/main/java/ru/practicum/explore/services/client/PrivateCommentService.java
> +    List<CommentDto> getComments(long userId);
супер!

2022-10-08 20:46 UTC, MadeOfSt0ne commented on server/src/main/java/ru/practicum/explore/controllers/admin/AdminCommentController.java
> +                                    @RequestParam(value = "text") String text) {
переделал

2022-10-08 21:01 UTC, MadeOfSt0ne commented on server/src/main/java/ru/practicum/explore/services/admin/AdminCommentService.java
> +public interface AdminCommentService {
ок. убрал интерфейсы

2022-10-08 21:22 UTC, MadeOfSt0ne commented on server/src/main/java/ru/practicum/explore/services/admin/AdminCommentService.java
> +    CommentDto editComment(long commentId, String text);
понял, принял, переделал

2022-10-08 21:25 UTC, MadeOfSt0ne commented on server/src/main/java/ru/practicum/explore/mappers/CommentMapper.java
> +    public static Comment toComment(String text, User author, Event event) {
теперь сервис сам создает новые коменты, про маппер знает только контроллер

2022-10-08 22:09 UTC, MadeOfSt0ne commented on stats/src/main/java/ru/practicum/stats/utils/DateTimeFormat/DateTimeFormat.java
> +public class DateTimeFormat {
У меня есть микросервисы A и B. Они могут работать в связке, а могут работать по отдельности, т.е. если B упал, то A посчитает что B вернул 0. B вообще ничего не знает про A и просто пишет/возвращает статистику. Если я добавлю сервис C, который по http запросу будет возвращать форматтер, и без которого не сможет работать ни один другой сервис, то зачем мне микросервисы?) Просто запихаю все в кучу и будет монолит =) Либо все работает, либо нет. Или это нормально, что ни один из основных микросервисов не может работать независимо от других модулей?? Еще и для тестов нужно будет мокать модуль. Работы на 2 дня минимум =\

2022-10-09 11:35 UTC, vbutrim commented on stats/src/main/java/ru/practicum/stats/utils/DateTimeFormat/DateTimeFormat.java
> +public class DateTimeFormat {
> Если я добавлю сервис C, который по http запросу будет возвращать форматтер, и без которого не сможет работать ни один другой сервис, то зачем мне микросервисы?)

не нужно добавлять сервис C. нужно сделать модуль C -- библиотеку, которую подтянут оба сервиса. это сделать 15 мин, 14 мин 30 секунд из которых придется на гугл.

2022-10-20 11:30 UTC, merged